/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cat.uvic.teknos.m09.cryptoutils;

import cat.uvic.teknos.m09.cryptoutils.Exceptions.MissingPropertiesException;
import cat.uvic.teknos.m09.cryptoutils.dto.DigestResult;

import java.io.IOException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.security.SecureRandom;
import java.util.Base64;
import java.util.HashMap;
import java.util.Properties;

public class Hash {
    Properties props;

    public  Hash() throws IOException {
        this.props = new Properties();
        //takes file properties from current classpath
        try{
            this.props.load(ClassLoader.getSystemClassLoader().getResourceAsStream("/cryptoutils.properties"));
        }catch(IOException| NullPointerException error){
            setDefaultProperties();
        }
    }

    public byte[] getHash(byte[] message) throws NoSuchAlgorithmException, MissingPropertiesException {

        String algorithm = this.props.getProperty("algorithm");

        if(algorithm == null){
            throw new MissingPropertiesException();
        }

        var messageDigest = MessageDigest.getInstance(algorithm);
        var salt  = this.props.getProperty("salt");

        if(salt!=null){
            messageDigest.update(salt.getBytes());
        }

        return messageDigest.digest(message);
    }

    public  String getHashAsString(byte[] message) throws NoSuchAlgorithmException, MissingPropertiesException {
        String algorithm = this.props.getProperty("algorithm");

        if(algorithm == null){
            throw new MissingPropertiesException();
        }

        var messageDigest = MessageDigest.getInstance(algorithm);
        var salt  = this.props.getProperty("salt");

        if(salt!=null){
            messageDigest.update(salt.getBytes());
        }

        var digest = messageDigest.digest(message);
        var base64Encoder = Base64.getEncoder();
        return base64Encoder.encodeToString(digest);

    }

    public DigestResult getHashWithRandomSalt(byte[] message) throws MissingPropertiesException, NoSuchAlgorithmException {
        DigestResult<byte[]> result;

        String algorithm = this.props.getProperty("algorithm");

        if(algorithm == null){
            throw new MissingPropertiesException();
        }

        var messageDigest = MessageDigest.getInstance(algorithm);
        var salt  = getRandomSalt();

        messageDigest.update(salt);
        result = new DigestResult(messageDigest.digest(message),algorithm,salt);

        return result;
    }

    public DigestResult getHashWithRandomSaltAsString(byte[] message) throws MissingPropertiesException, NoSuchAlgorithmException {
        DigestResult<String> result;

        String algorithm = this.props.getProperty("algorithm");

        if(algorithm == null){
            throw new MissingPropertiesException();
        }

        var messageDigest = MessageDigest.getInstance(algorithm);
        var salt  = getRandomSalt();

        messageDigest.update(salt);

        var digest = messageDigest.digest(message);
        var base64Encoder = Base64.getEncoder();
        String hashResult = base64Encoder.encodeToString(digest);

        result = new DigestResult<>(hashResult,algorithm,new String(salt));

        return result;
    }

    //takes file properties from Library resources
    public void setDefaultProperties() throws IOException {
        this.props.load(Hash.class.getResourceAsStream("/cryptoutils.properties"));
    }

    public Properties getProps(){
        return this.props;
    }

    public static byte[] getRandomSalt(){
        var secureRandom = new SecureRandom();
        var salt  = new byte[16];
        secureRandom.nextBytes(salt);
        return salt;
    }
}
