/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cat.uvic.teknos.m09.elbouzzaouiabdelkarim.cryptoutils;

import cat.uvic.teknos.m09.elbouzzaouiabdelkarim.cryptoutils.Exceptions.MissingPropertiesException;
import cat.uvic.teknos.m09.elbouzzaouiabdelkarim.cryptoutils.dto.DigestResult;

import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.security.SecureRandom;
import java.util.Base64;

public  class Hash extends PropertiesImp{

    private static String ALGORITHM = "algorithm";
    public  byte[] getHash(byte[] message) throws NoSuchAlgorithmException, MissingPropertiesException {

        String algorithm = props.getProperty("algorithm");

        if(algorithm == null){
            throw new MissingPropertiesException();
        }

        var messageDigest = MessageDigest.getInstance(algorithm);
        var salt  = props.getProperty("salt");

        if(salt!=null){
            messageDigest.update(salt.getBytes());
        }

        return messageDigest.digest(message);
    }

    public String getHashAsString(byte[] message) throws NoSuchAlgorithmException, MissingPropertiesException {
        String algorithm = props.getProperty("algorithm");

        if(algorithm == null){
            throw new MissingPropertiesException();
        }

        var messageDigest = MessageDigest.getInstance(algorithm);
        var salt  = props.getProperty("salt");

        if(salt!=null){
            messageDigest.update(salt.getBytes());
        }

        var digest = messageDigest.digest(message);
        var base64Encoder = Base64.getEncoder();
        return base64Encoder.encodeToString(digest);

    }

    public DigestResult getHashWithRandomSalt(byte[] message) throws MissingPropertiesException, NoSuchAlgorithmException {
        DigestResult<byte[]> result;

        String algorithm = props.getProperty("algorithm");

        if(algorithm == null){
            throw new MissingPropertiesException();
        }

        var messageDigest = MessageDigest.getInstance(algorithm);
        var salt  = getRandomSalt();

        messageDigest.update(salt);
        result = new DigestResult(messageDigest.digest(message),algorithm,salt);

        return result;
    }

    public DigestResult getHashWithRandomSaltAsString(byte[] message) throws MissingPropertiesException, NoSuchAlgorithmException {
        DigestResult<String> result;

        String algorithm = props.getProperty("algorithm");

        if(algorithm == null){
            throw new MissingPropertiesException();
        }

        var messageDigest = MessageDigest.getInstance(algorithm);
        var salt  = getRandomSalt();

        messageDigest.update(salt);

        var digest = messageDigest.digest(message);
        var base64Encoder = Base64.getEncoder();
        String hashResult = base64Encoder.encodeToString(digest);

        result = new DigestResult<>(hashResult,algorithm,new String(salt));

        return result;
    }

    public  byte[] getRandomSalt(){
        var secureRandom = new SecureRandom();
        var salt  = new byte[16];
        secureRandom.nextBytes(salt);
        return salt;
    }
}
